# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Justin Lee
  url:        http://justin94lee.GitHub.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
