# Site
title:              "Machine"
bio:                'Live Alone and Prosper'
description:        "Justin Lee"
reading_time:       false
words_per_minute:   200
logo:               'assets/img/LOGO.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             zh_CN
url:                http://justin94lee.github.io

# Jekyll
permalink:          /:title.html/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   J.Lee
# # page botton
# {% if page.previous %}
#   {% comment %} url:    page.previous.url {% endcomment %}
#   {% comment %} title:  page.previous.title | truncatewords:5 {% endcomment %}
# {% endif %}
# {% if page.next %}
#   {% comment %} url:    page.next.url {% endcomment %}
#   {% comment %} title:  page.next.url | truncatewords:5 {% endcomment %}
# {% endif %}
#
# # paginator
# {% for post in paginator.posts %}
#   {% comment %} 输出当前分页的所有文章 {% endcomment %}
#   {{ post.content }}
# {% endfor %}

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            justinleeig
#facebook:           username
github:             justin94lee
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          justin94lee
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
